# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  imageTag: docker-registry.wayproyect.com/blogifier

stages:
  - stage: Build
    jobs:
    - job: BuildSrc
      steps:
      - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'
  - stage: Test
    jobs:
    - job: TestSrc
      steps:
      - script: echo No Tests
  - stage: Deploy
    jobs:
    - job: Deploy
      steps:
      - script: |
          docker-compose build
          docker login -u $(user) -p $(pswd) docker-registry.wayproyect.com
          docker push $(imageTag)
        env:
          user: $(dockerUser)
          pswd: $(dockerPassword)
        displayName: 'docker push $(imageTag)'