# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: |
      dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: |
      dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=%CI_PROJECT_ROOT_PATH%/utests_results/ /p:Exclude=[xunit*]*
  displayName: 'dotnet tests'
# - script: |
#       docker build -f ./src/App/Dockerfile -t docker-registry.wayproyect.com/blogifier:amd64 .
#   displayName: 'build docker image tests docker-registry.wayproyect.com/blogifier'
# - script: |
#     docker-compose build
#     docker login -u $(user) -p $(pswd) docker-registry.wayproyect.com
#     docker push $(imageTag)
#   env:
#     user: $(dockerUser)
#     pswd: $(dockerPassword)
#   displayName: 'docker push $(imageTag)'