# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  imageTag: docker-registry.wayproyect.com/blogifier

steps:
- script: |
    docker-compose build
    docker login -u $(dockerUser) -p $(dockerPassword) docker-registry.wayproyect.com
    docker push $(imageTag)
  displayName: 'docker push $(imageTag) $(dockerUser)'