version: '3.4'

services:
  blogifier:
    image: blogifier
    container_name: blogifier
    build:
      context: .
      dockerfile: src/App/Dockerfile
    volumes:
      - ./volumes/app/wwwroot:/app/wwwroot
      - ./volumes/app/app.db:/app/app.db
    restart: on-failure
    ports:
      - "5002:80"
    